package com.careindia.lifeskills.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "tblPDC")
data class PrimaryDataEntity(
    @PrimaryKey @ColumnInfo(name = "PDCGUID") val PDCGUID: String,
    @ColumnInfo(name = "IMGUID") val IMGUID: String?="",
    @ColumnInfo(name = "HHGUID") val HHGUID: String?="",
    @ColumnInfo(name = "StateCode") val StateCode: Int? =0,
    @ColumnInfo(name = "DistrictCode") val DistrictCode: Int?,
    @ColumnInfo(name = "ZoneCode") val ZoneCode: Int?,
    @ColumnInfo(name = "Panchayat_Ward") val Panchayat_Ward: Int?,
    @ColumnInfo(name = "PWCode") val PWCode: String?="",
    @ColumnInfo(name = "Locality") val Locality: String? = "",
    @ColumnInfo(name = "CollectionDate") val CollectionDate: Long?,
    @ColumnInfo(name = "Crpid") val Crpid: Int,
    @ColumnInfo(name = "fcid") val fcid: Int,
    @ColumnInfo(name = "CommunityName") val CommunityName: String?,
    @ColumnInfo(name = "Name") val Name: String? = "",
    @ColumnInfo(name = "Age") val Age: Int? = 0,
    @ColumnInfo(name = "Gender") val Gender: Int?,
    @ColumnInfo(name = "Contact") val Contact: String?,
    @ColumnInfo(name = "Group_Link") val Group_Link: Int?,
    @ColumnInfo(name = "SocialCategory") val SocialCategory: Int?,
    @ColumnInfo(name = "CastIncomeCertificate") val CastIncomeCertificate: Int?,
    @ColumnInfo(name = "ValidAadhaar") val ValidAadhaar: Int?,
    @ColumnInfo(name = "ValidPAN") val ValidPAN: Int?,
    @ColumnInfo(name = "ValidBank") val ValidBank: Int?,
    @ColumnInfo(name = "Business_Interested") val Business_Interested: Int?,
    @ColumnInfo(name = "Training_skills") val Training_skills: Int?,
    @ColumnInfo(name = "Business_Training") val Business_Training: String?,
    @ColumnInfo(name = "Business_Plan") val Business_Plan: Int?,
    @ColumnInfo(name = "Business_Investment_Amt") val Business_Investment_Amt: String?,
    @ColumnInfo(name = "Invest_readiness") val Invest_readiness: Int?,
    @ColumnInfo(name = "Invest_HowMuch") val Invest_HowMuch: Int?,
    @ColumnInfo(name = "Invest_Plan") val Invest_Plan: String?,
    @ColumnInfo(name = "Invest_Plan_Oth") val Invest_Plan_Oth: String?,
    @ColumnInfo(name = "Financial_Assistance") val Financial_Assistance: Int?,
    @ColumnInfo(name = "Invest_support") val Invest_support: Int,
    @ColumnInfo(name = "Invest_support_Oth") val Invest_support_Oth: String,
    @ColumnInfo(name = "Loan_interested") val Loan_interested: Int,
    @ColumnInfo(name = "Loan_Source") val Loan_Source: Int,
    @ColumnInfo(name = "Loan_Source_Oth") val Loan_Source_Oth: String,
    @ColumnInfo(name = "Loan_amount") val Loan_amount: String,
    @ColumnInfo(name = "Amt_Invested") val Amt_Invested: String,
    @ColumnInfo(name = "Business_type") val Business_type: String,
    @ColumnInfo(name = "Business_Invest_Source") val Business_Invest_Source: Int,
    @ColumnInfo(name = "Business_registered") val Business_registered: Int,
    @ColumnInfo(name = "Stage_Self_Emp") val Stage_Self_Emp: Int,
    @ColumnInfo(name = "Stage_Self_Emp_Oth") val Stage_Self_Emp_Oth: String,
    @ColumnInfo(name = "Loan_availed") val Loan_availed: Int,
    @ColumnInfo(name = "Loan_availed_from") val Loan_availed_from: Int,
    @ColumnInfo(name = "Financial_assist") val Financial_assist: Int,
    @ColumnInfo(name = "Financial_assist_amt") val Financial_assist_amt: Int,
    @ColumnInfo(name = "Support_Expecting") val Support_Expecting: String?="",
    @ColumnInfo(name = "Support_Expecting_Oth") val Support_Expecting_Oth: String,
    @ColumnInfo(name = "CreatedBy") val CreatedBy: Int?,
    @ColumnInfo(name = "CreatedOn") val CreatedOn: Long?,
    @ColumnInfo(name = "UpdatedBy") val UpdatedBy: Int?,
    @ColumnInfo(name = "UpdatedOn") val UpdatedOn:Long?,
    @ColumnInfo(name = "SyncOn") val SyncOn:String?="",
    @ColumnInfo(name = "Status") val Status: Int?,
    @ColumnInfo(name = "Actionby") val Actionby: Int?,
    @ColumnInfo(name = "IsEdited") val IsEdited: Int = 0,
    @ColumnInfo(name = "Name_Collective") val Name_Collective: String?="",
    @ColumnInfo(name = "Training_Days") val Training_Days: String?="",
    @ColumnInfo(name = "Business_Start") val Business_Start: String?="",
    @ColumnInfo(name = "Business_Start_Othr") val Business_Start_Othr: String?="",
    @ColumnInfo(name = "Business_Training_Othr") val Business_Training_Othr: String?,
    @ColumnInfo(name = "Business_Invested_Othr") val Business_Invested_Othr: String?,
    @ColumnInfo(name = "Remarks") val Remarks: String? = "",
    @ColumnInfo(name = "StateID") val StateID: Int? =0,
    @ColumnInfo(name = "ProcessID") val ProcessID: Int? =0,
    @ColumnInfo(name = "Business_Name") val Business_Name: String? ="",
    @ColumnInfo(name = "Business_Stage_ID") val Business_Stage_ID: Int? =0,
    @ColumnInfo(name = "Business_Stage_Othr") val Business_Stage_Othr: String? ="",
    @ColumnInfo(name = "Investment_Mode") val Investment_Mode: String? ="",
    @ColumnInfo(name = "Investment_Mode_Othr") val Investment_Mode_Othr: String? ="",
    @ColumnInfo(name = "Self_Amount_Invested") val Self_Amount_Invested: Int? =0,
    @ColumnInfo(name = "Investment_Mode_Purpose") val Investment_Mode_Purpose: String? ="",
    @ColumnInfo(name = "Loan_Repayment") val Loan_Repayment: Int? =-1,
    @ColumnInfo(name = "Loan_Amount_Returned") val Loan_Amount_Returned: Int? =0,
    @ColumnInfo(name = "Loan_Interest_Returned") val Loan_Interest_Returned: Int? =0,
    @ColumnInfo(name = "Non_Repayment_Reason") val Non_Repayment_Reason: String? ="",
    @ColumnInfo(name = "Business_Support_ID") val Business_Support_ID: Int? =0,
    @ColumnInfo(name = "Business_Support_Othr") val Business_Support_Othr: String? ="",
    @ColumnInfo(name = "Asset_Support_Kind") val Asset_Support_Kind: String? ="",
    @ColumnInfo(name = "Cost_Asset") val Cost_Asset: String? ="",
    @ColumnInfo(name = "Skill_Training_Nature") val Skill_Training_Nature: String? ="",
    @ColumnInfo(name = "Skill_Training_Nature_Othr") val Skill_Training_Nature_Othr: String? ="",
    @ColumnInfo(name = "Total_Training_Cost") val Total_Training_Cost: Int? =0,
    @ColumnInfo(name = "Training_Helped_Business") val Training_Helped_Business: String? ="",
    @ColumnInfo(name = "Market_Linkage_ID") val Market_Linkage_ID: Int? =0,
    @ColumnInfo(name = "Market_Linkage_Othr") val Market_Linkage_Othr: String? ="",
    @ColumnInfo(name = "Market_Linkage_Amount") val Market_Linkage_Amount: Int? =0,
    @ColumnInfo(name = "Branding_Support_ID") val Branding_Support_ID: Int? =0,
    @ColumnInfo(name = "Branding_Support_Othr") val Branding_Support_Othr: String? ="",
    @ColumnInfo(name = "Branding_Support_Amount") val Branding_Support_Amount: Int? =0,
    @ColumnInfo(name = "Expenses_Month") val Expenses_Month: Int? =0,
    @ColumnInfo(name = "Sales_Month") val Sales_Month: Int? =0,
    @ColumnInfo(name = "Profit_Month") val Profit_Month: Int? =0,
    @ColumnInfo(name = "Money_Invested_Month") val Money_Invested_Month: Int? =0,
    @ColumnInfo(name = "Net_Saving_Month") val Net_Saving_Month: Int? =0,
    @ColumnInfo(name = "Finance_Support_Source") val Finance_Support_Source: String? ="",
    @ColumnInfo(name = "Finance_Support_Purpose") val Finance_Support_Purpose: String? ="",
    @ColumnInfo(name = "Finance_Support_Amount") val Finance_Support_Amount: Int? =0,
    @ColumnInfo(name = "Finance_Support_Interest") val Finance_Support_Interest: Int? =0,
    @ColumnInfo(name = "Business_Running_Smoothly") val Business_Running_Smoothly: Int? = -1,
    @ColumnInfo(name = "Business_Reason_ID") val Business_Reason_ID: Int? =0,
    @ColumnInfo(name = "Business_Reason_Othr") val Business_Reason_Othr: String? ="",
    @ColumnInfo(name = "Successful_Business_Attri") val Successful_Business_Attri: String? =""
)

